### ISSUE TITLE
If the dataframe to clean has columns that are named the same as any of the flags, they get overwritten

### ISSUE THREAD

**Issue by andrewjbe** [openjusticeok/ojoregex#21]
I think I should probably just add some kind of prefix or something, maybe there's an rlang way to handle it?

**Comment by brancengregory** [comment]
We can mimic the cli response of `dplyr` when you do joins not on columns of the same name, e.g. two ojodb tables that have `id` columns, but `x.id == y.case_id`, resulting in an `x.id` column and a `y.id` column. We just need to think about the prefix.

Another option is to have it be strict and not continue the operation if it detects a column with the same name as one to be created, and passing a `prefix` or `suffix` argument to solve the contradiction. This is half of what `dplyr` does.

Let's discuss desired behavior with the whole team.
